=== DavevanIersel/WinDash2/widgets/widget-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "Generated from filename"
      },
      "name": {
        "type": "string",
        "description": "A name for the widget"
      },
      "html": {
        "type": "string",
        "description": "The HTML page that should be loaded for a custom widget"
      },
      "url": {
        "type": "string",
        "description": "The URL which should be loaded"
      },
      "x": {
        "type": "number",
        "description": "Horizontal position of the upper left corner of the widget"
      },
      "y": {
        "type": "number",
        "description": "Vertical position of the upper left corner of the widget"
      },
      "width": {
        "type": "number",
        "description": "Width of the widget"
      },
      "height": {
        "type": "number",
        "description": "Height of the widget"
      },
      "touchEnabled": {
        "type": "boolean",
        "description": "Indicates whether touch controls are simulated, especially great in combination with a mobile user agent"
      },
      "enabled": {
        "type": "boolean",
        "description": "Toggle widget on or off"
      },
    
      "customUserAgent": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "domain": {
              "type": "string",
              "description": "The domain to which this custom user agent applies"
            },
            "userAgent": {
              "type": "string",
              "description": "The custom user agent string for the specified domain"
            }
          },
          "required": ["domain", "userAgent"]
        },
        "description": "A list of custom user agents for specific domains"
      },
      "permissions": {
        "type": "object",
        "additionalProperties": {
          "type": "boolean",
          "description": "Indicates whether a specific permission is granted"
        },
        "description": "Mapping of permission types (strings) to booleans"
      },
      "customScript": {
        "type": "string",
        "description": "A custom JS script you want to be loaded on the widget webpage"
      },
      "devTools": {
        "type": "boolean",
        "description": "Enable developer tools for this widget"
      },
      "forceInCurrentTab": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Specifies URLs or domains to block from opening in separate tabs"
        },
        "description": "A list of URLs or domains to block from opening in separate tabs"
      }
    },
    "anyOf": [
      {
        "required": ["html"],
        "not": {
          "required": ["url"]
        }
      },
      {
        "required": ["url"],
        "not": {
          "required": ["html"]
        }
      }
    ],
    "required": [
      "name",
      "x",
      "y",
      "width",
      "height",
      "enabled"
    ],
    "additionalProperties": true
  }

=== DavevanIersel/WinDash2/widgets/google.widget.json
{
  "$schema": "widget-schema.json",
  "name": "Spotify",
  "url": "https://google.nl/",
  "enabled": false,
  "x": 2,
  "y": 11,
  "width": 15,
  "height": 8,
  "touchEnabled": true,
  "customUserAgent": [
    {
      "domain": "open.spotify.com",
      "userAgent": "Mozilla/5.0 (Android 15; Mobile; rv:133.0) Gecko/133.0 Firefox/133.0"
    }
  ]
}

=== DavevanIersel/WinDash2/widgets/spotify.widget.json
{
  "$schema": "widget-schema.json",
  "name": "Spotify",
  "url": "https://open.spotify.com",
  "enabled": false,
  "x": 3295,
  "y": 208,
  "width": 832,
  "height": 464,
  "touchEnabled": true,
  "customUserAgent": [
    {
      "domain": "open.spotify.com",
      "userAgent": "Mozilla/5.0 (Android 15; Mobile; rv:133.0) Gecko/133.0 Firefox/133.0"
    }
  ],
  "permissions": {
    "mediaKeySystem": true
  }
}
